### ISSUE TITLE
which clock?

### ISSUE THREAD

**Issue by jotego** [ika-musume/IKAOPM#11]
In the schematics, what is the assumed clock in flip flops where the connection is not shown? Like these ones in the _noise_ schematic:

![image](https://github.com/ika-musume/IKAOPM/assets/1863036/684aa7ec-0c5d-4887-b426-3812134fdde7)

**Comment by jotego** [comment]
Are all these flip flops really missing a /reset pin?

**Comment by ika-musume** [comment]
1. negative edge of phi1
2. Yes. The flip-flops that make up the noise module are all shift registers, made up of two NMOS transfer gates, two capacitor, and two inverters. The system reset is performed by external gates, such as an AOI21.
